server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: '${EUREKA_URI:http://localhost:8761/eureka/}'
spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      file-size-threshold: 20KB
  application:
    name: medico-gateway
  cloud:
    gateway:
      routes:
        - id: medico-booking-service
          uri: lb://MEDICO-BOOKING
          predicates:
            - Path=/booking/**
          filters:
            - StripPrefix=1
ribbon:
   ReadTimeout: 90000
   ConnectTimeout: 90000
hystrix:
   command:
      default:
         execution:
            isolation:
               thread:
                  timeoutInMilliseconds: 60000
